### ISSUE TITLE
Problems with project setup

### ISSUE THREAD

**Issue by davidwesst** [mikesigs/wpgdotnetui#1]
It appears that I'm having problems running _npm install_ and actually displaying anything on the page when I occasionally get things running.

More specifically-- I get the following error regarding PYTHON when I run `npm install`

> Error: Can't find Python executable "python", you can set the PYTHON env variable.

...and when I run `gulp build` I get:

> ERROR in Entry module not found: Error: Cannot resolve module 'awesome-typescript-loader' in C:\code\wpgdotnetug\wpgdotnetui

---

It seems like an environment issue. What version of NPM and NodeJS you are running get this solution working?

**Comment by mikesigs** [comment]
Odd about Python. It shouldn't be a requirement, or at least need to be separately installed. That said, I do have it on my machine.

Did you also run `bower install`?

**Comment by mikesigs** [comment]
I am using node 4.2.4 and npm 3.5.3. Also, I have Python 2.7.10 installed.

**Comment by mikesigs** [comment]
I uninstalled Python and sure enough `npm install` fails with the same error. Looks like the `node-gyp` package requires it. Are you running this on Windows by chance? I think you've talked about chocolatey before, haven't you? If you have it installed just run `cinst python2` then try `npm install` again.

**Comment by davidwesst** [comment]
That did the trick! Thanks for the guidance.
